[package]
name = "franzplot-compute"
version = "0.1.0"
authors = ["francesco.cattoglio <francesco.cattoglio@gmail.com>"]
edition = "2018"

[[bin]]
name = "franzplot"
path = "src/main.rs"

[dependencies]
bytemuck = "1.2"
wgpu = "0.6"
shaderc = "0.6"
anyhow = "1.0"
futures = "0.3"
glam = "0.11"
maplit = "1.0"
winit = "0.23"
tobj = "2.0"
image = "0.23"
smol_str = { version = "0.1", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
ron = "0.6.4"
getopts = "0.2"
obj = "0.10"
imgui = "0.6.0"
imgui-wgpu = "0.12.0"
wgpu-subscriber = "0.1"
cxx = "1.0.9"
pathfinding = "2.0"
indexmap = "1.6"
tinyfiledialogs = "3"
hexasphere = "3.1"

[dependencies.imgui-winit-support]
version = "0.6"

[build-dependencies]
cxx-build = "1.0"

[profile.dev.package.image]
opt-level = 2
