[package]
name = "franzplot-compute"
version = "0.1.0"
authors = ["francesco.cattoglio <francesco.cattoglio@gmail.com>"]
edition = "2018"

[dependencies]
bytemuck = "1.2"
wgpu = "0.6"
shaderc = "0.6"
anyhow = "1.0"
futures = "0.3"
glam = { version = "0.10", features = ["debug-glam-assert"] }
maplit = "1.0"
winit = "0.23"
tobj = "2.0"
image = "0.23"
smol_str = { version = "0.1", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_jsonrc = "0.1"
getopts = "0.2"
imgui = "0.6.0"
imgui-wgpu = "0.12.0"
wgpu-subscriber = "0.1"
cxx = "1.0"
pathfinding = "2.0"
indexmap = "1.6"

[dependencies.imgui-winit-support]
version = "0.6"
default-features = false
features = ["winit-23"]

[build-dependencies]
cxx-build = "1.0"
