[package]
name = "franzplot-compute"
version = "0.1.0"
authors = ["francesco.cattoglio <francesco.cattoglio@gmail.com>"]
edition = "2018"

[dependencies]
bytemuck = "1.2"
wgpu = "0.6"
shaderc = "0.6"
anyhow = "1.0"
futures = "0.3"
ultraviolet = "0.4.6"
maplit = "1.0"
winit = "0.22"
tobj = "2.0"
image = "0.22"
itertools = "0.8"
smol_str = { version = "0.1", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_jsonrc = "0.1"
getopts = "0.2"
imgui = "0.5.0"
imgui-wgpu = "0.10.0"
wgpu-subscriber = "0.1"
cxx = "0.4"

[dependencies.imgui-winit-support]
version = "0.5"
default-features = false
features = ["winit-22"]

[build-dependencies]
cxx-build = "0.4"
