[package]
name = "franzplot-compute"
version = "0.1.0"
authors = ["francesco.cattoglio <francesco.cattoglio@gmail.com>"]
edition = "2018"

[dependencies]
bytemuck = "1.2"
wgpu = "0.5.2"
shaderc = "0.6"
anyhow = "1.0"
futures = "0.3"
downcast-rs = "1.2.0"
