[package]
name = "franzplot-compute"
version = "0.1.0"
authors = ["francesco.cattoglio <francesco.cattoglio@gmail.com>"]
edition = "2018"

[[bin]]
name = "franzplot"
path = "src/main.rs"

[dependencies]
bytemuck = "1.2"
wgpu = "0.7"
shaderc = "0.7"
anyhow = "1.0"
futures = {version="0.3.10",features=["thread-pool"]}
glam = "0.11"
maplit = "1.0"
winit = "0.24"
tobj = "2.0"
image = "0.23"
smol_str = { version = "0.1", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
ron = "0.6.4"
getopts = "0.2"
obj = "0.10"
imgui = "0.7.0"
imgui-winit-support = "0.7.0"
imgui-wgpu = "*"
wgpu-subscriber = "0.1"
cxx = "1.0.9"
pathfinding = "2.0"
indexmap = "1.6"
nfd2 = "0.2"
hexasphere = "3.1"

#TODO: when a new release happens, just switch back to normal rfd from crates.io
rfd = { git = "https://github.com/PolyMeilex/rfd.git", rev = "7b5e29f" }

[build-dependencies]
cxx-build = "1.0"

[profile.dev.package.image]
opt-level = 2

[patch.crates-io]
imgui-wgpu = { git = 'https://github.com/4bb4/imgui-wgpu-rs.git', branch = 'upgrade-to-imgui-rs-0.7' }

