name: MacOS Catalina Build

on: workflow_dispatch

env:
  MACOSX_DEPLOYMENT_TARGET: 10.11

jobs:
  build_and_test:
    name: Rust project
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Release binary
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: target/release/franzplot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
