name: Ubuntu 20.04 Build

on: workflow_dispatch

env:
  MACOSX_DEPLOYMENT_TARGET: 10.11

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Release binary
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ubuntu_22_03
          files: target/release/franzplot
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
